  - hosts: all
    become: true
    pre_tasks:
  
    - name: install updates (Ubuntu) 
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"


###  WEB SERVER ####

  - hosts: web_servers
    become: true
    tasks: 

    - name: install apache and php for Ubuntu servers
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
  
    - name: start apache2
      tags: apache2,apache
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: change email address for admin
      tags: apache,serveradmin
      ansible.builtin.lineinfile:
        path: /etc/apache2/sites-enabled/000-default.conf
        regexp: '^ServerAdmin'
        line: 'ServerAdmin ubuntu@ubuntu.net'
      register: apache2

    - name: restart apache
      tags: apache,serveradmin
      service:
        name: apache2
        state: restarted
      when: apache2.changed
         

    - name: copy html file to /var/www/html
      tags: html, file
      copy:
        src: ~/projects/ansible/ansible/files/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: install unzip
      package:
        name: unzip

    #- name: copy terraform package
     # tags: terraform
      #copy:
       # src: /files/terraform.zip
        #dest: /home/ubuntu/terraform.zip
        #remote_src: yes
        #owner: root
        #group: root
        #mode: 0775

    - name: install terraform
      tags: terraform
      unarchive:
        src: /home/ubuntu/terraform.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root


  # DB SERVER # 

  - hosts: db_servers
    become: true
    tasks: 

    - name: install MySQL server
      tags: mysql
      apt: 
        name: mysql-server
        state: latest
        update_cache: yes
